services:
  om3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./flags:/app/flags
  om3_encoder:
    build: 
      context: ./encoder
      dockerfile: Dockerfile
    ports:
      - 3330:3330
    volumes:
      - ./flags/single_line:/app/flags
  om3_db:
    build: 
      context: ./
      dockerfile: DB_Dockerfile
    ports:
      - 6432:5432
    volumes:
        - data_volume:/var/lib/postgresql/data/pgdata
volumes:
  data_volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/chun/project/jsproject/om3/responsive_linechart_srv/om3-server/data
      o: bind    
